### PR TITLE
Add Italian to available languages

### PR DESCRIPTION
**Pull request by carlogrisetti**

### CODE REVIEW

**Comment by padmalcom** [comment]
Hi Carlo, looks good to me. Do you plan to add further improvements (e.g. adding italian to main_text_gen_gpt2.py)? If not, just tell me and I'll do the rest and merge.

**Comment by carlogrisetti** [comment]
I don't really know at this point... I am adding things as I go, and I do not really plan to use gpt2 (wiki is more than enough for what I would like to try)
On my fork I added texts and samples to the gitignore. I think they should be excluded from the repo.
Also maybe setting the default language to "en" instead of "de", but those are all cosmetic improvements

**Comment by padmalcom** [comment]
Okay, then let me merge for now and see what else is coming.

**Comment by padmalcom** [comment]
Merged and added GPT2 generation for Italian.

**Pull request merged**
